import type { Metadata } from "next";
import "./globals.css";
import ClientProviderWrapper from "./ClientProviderWrapper";

export const metadata: Metadata = {
  title: "Mars Rover Image Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Exo+2:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="antialiased"
        style={{
          background: "linear-gradient(to bottom, #0d1117, #1a1f26, #2b3240)",
          color: "#ffffff",
          fontFamily: '"Exo 2", sans-serif',
        }}
      >
        <ClientProviderWrapper>{children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
